import sys,os
import Lib,Utils,Server

ARGV = sys.argv[1:]

def make_Init():
    files = os.listdir("./HostedData/Scripts")
    SLASH = '/'
    output = """##############################
                #    DO NOT EDIT THIS FILE   #
                ##############################
        """.replace('        ','')
    for x in files:
        if not "__" in x:
            if not ".py" in x:
                output+=f"from . import {x.split(SLASH)[-1]}\n"
            else:
                output+=f"from . import {(x.split(SLASH)[-1]).split('.py')[0]}\n"
    output+= """'''
                This file is specific for python formatting.
                This allows <rootDir>/HostedData/Scripts/*.py to be imported. (aka all the py files.)
                '''
        """.replace('        ','')
    with open("HostedData/Scripts/__init__.py",'w') as f:
        f.write(output)
    
def make_user(name, size,password):
    username = Utils.hashString(name)
    Utils.GenKey(username, size, name,password)

if __name__ == '__main__':
    config = Utils.get_Config()
    if ARGV[0] == "startServer":
        make_Init()
        import HostedData
        #Lib.GlobalData.Data["Scripts"]["EXAMPLE"]["Functions"]["pog"]()
        Server.server(config)
    if ARGV[0] == "NewUser":
        make_user(ARGV[1],config["Encryption"]["Size"],ARGV[2].encode())